### ISSUE TITLE
Support item updates by key

### ISSUE THREAD

**Issue by butenkor** [sphereio/sphere-node-sdk#102]
Currently most update actions require item ID. API supports now updates over unique and user specific keys. Example: http://dev.commercetools.com/http-api-projects-productTypes.html#update-product-type-by-key

**Comment by emmenko** [comment]
Is it only for product types?

**Comment by butenkor** [comment]
Not only: 
http://dev.commercetools.com/http-api-projects-types.html#update-type-by-key

Looking [at support request](http://support.sphere.io/forums/201737-api/suggestions/9252435-external-key-for-product-types-attributes) more is to come. Would be also useful for tax categories and customer groups for example. Maybe @yanns can provide more info.

**Comment by yanns** [comment]
The idea is to support the `key` for all resources.
