### ISSUE TITLE
limit=0 was deprecated, all() is not working anymore

### ISSUE THREAD

**Issue by mmoelli** [sphereio/sphere-node-sdk#105]

**Comment by emmenko** [comment]
`limit=0` is never actually used. It's just an indicator that the sdk has to fetch all pages.

What's the original problem here?

**Comment by emmenko** [comment]
The problem occurs if you use `all` together with the `process` function, which doesn't make any sense per-se.
We should simply add a check to use a default value if `perPage` is set to `0` (in the `process` function).
