### ISSUE TITLE
SDK returns by default statusCode = 500 if there were no response from server

### ISSUE THREAD

**Issue by butenkor** [sphereio/sphere-node-sdk#113]
If internet connection is broken or request times out SDK will return statusCode = "500" on request to CTP API. This is confusing. It should set status code "unknown" or not set it at all.

**Comment by OlegIlyenko** [comment]
+1

**Comment by emmenko** [comment]
There should always be a status code. And if the error is not coming from the API (e.g. timeout), you can see that from the error type (`HttpError`).

**Comment by emmenko** [comment]
A `500` from the API has a `InternalServerError` type

**Comment by butenkor** [comment]
If you set timeout in "request" lib to something small like "100" lib will throw own error without waiting for API to response and produce an error with statusCode = 500. How useful is that? Same thing if connection is broken.

**Comment by butenkor** [comment]
I agree that there should always be some reason in error or status code. But 500 is server error and in above cases it is not and confusing.

**Comment by emmenko** [comment]
So what you want is to remove the `or 500` here, right?

https://github.com/sphereio/sphere-node-sdk/blob/master/src/coffee/services/base.coffee#L564

**Comment by OlegIlyenko** [comment]
I also find this default pretty confusing. Http status code has pretty clear semantics, namely that it comes from the server.

**Comment by butenkor** [comment]
@emmenko Probably. Ideally looking at error i would like to know if error was produced by API or some other reasons. Status code implies response from API

**Comment by emmenko** [comment]
Alright, we remove the `or 500` then. If the error is not coming from the API, it's a `HttpError` error type.

**Comment by OlegIlyenko** [comment]
:+1:

**Comment by PhilippSpo** [comment]
agreed. Maybe `ConnectionError` or something similar would have been a better/less confusing error name also ..
