### ISSUE TITLE
Prevent Images from being deleted on the CDN

### ISSUE THREAD

**Issue by PhilippSpo** [sphereio/sphere-node-sdk#114]
### Actual behavior
When updating the label or dimensions of an image, the SDK generates a remove and an add action for this image, since there are no update actions for images in the API. Since the image is removed, it also gets removed from the CDN and would need to be reuploaded as a new image

### Expected behavior
Images are not deleted from CDN. This is currently only possible when preventing labels and dimensions from being updated, because this would result in a remove + add action (which deletes the image from the CDN).
It should be however still be possible to change the URL of a image, and then it is fine when the image gets removed from the CDN, since we use a new image/url anyway.

This will also fix an [issue](https://github.com/sphereio/sphere-node-product-csv-sync/issues/111) in the node-product-csv-sync.

**Comment by emmenko** [comment]
You might want to look at the new implementation, it might solve the problem

https://github.com/sphereio/merchant-center-frontend/commit/c5d1fee6596818eae8b2ee185b5e10ca1a564763

**Comment by PhilippSpo** [comment]
@emmenko yup it does.. That's the overhead of having both versions around I guess ..
