### ISSUE TITLE
Only last of multiple query parameters remain in query, in some circumstances.

### ISSUE THREAD

**Issue by louis-adiputra** [sphereio/sphere-node-sdk#117]
I created a request using 2 ``expand()`` parameters.

``client.productProjections.staged(true).where(sku in ("some-sku")').expand('masterVariant.prices[*].channel').expand('variants[*].prices[*].channel').all().fetch()``

### Expected behavior
The generated query contains 2 ``expand`` parameters because I called ``.expand()`` twice.

### Actual behavior

The generated query contains only 1 ``expand`` parameter.

### Steps to reproduce the behavior

See above.

Problem does not occur if I use ``.perPage(100)`` instead of ``.all()`` in the query.

Tracing the problem, if I use ``all()``, ``perPage`` is set to 0, the if condition at https://github.com/sphereio/sphere-node-sdk/blob/c75a5ca29121a072f776d7f2e67336ad381f412b/src/coffee/services/base.coffee#L287 evaluates to true (at least in my case...) and ``@_paged()`` is called. 

Inside this method, ``@_rest.PAGED()`` is called, and there ``_.parseQuery()`` is called:
https://github.com/sphereio/sphere-node-sdk/blob/c75a5ca29121a072f776d7f2e67336ad381f412b/src/coffee/connect/rest.coffee#L184
 but without the ``false`` parameter: https://www.npmjs.com/package/underscore-mixins#_parsequery , so the 1st ``expand``parameter disappears.

**Comment by emmenko** [comment]
@louis-adiputra good catch, thanks! 
/cc @PhilippSpo
