### ISSUE TITLE
TypeError: Cannot read property 'request' of undefined

### ISSUE THREAD

**Issue by butenkor** [sphereio/sphere-node-sdk#140]
### Expected behavior
Schould return Promise.reject() with error details
### Actual behavior
On request it throws an error:
TypeError: Cannot read property 'request' of undefined
InventoryEntryService.BaseService._wrapResponse (/app/node_modules/sphere-stock-import/node_modules/sphere-node-sdk/lib/services/base.js:378:27
### Steps to reproduce the behavior
Hard to reproduce as it happens only in some cases related to connection

**Comment by butenkor** [comment]
Probably happens here: https://github.com/sphereio/sphere-node-sdk/blob/master/src/coffee/services/base.coffee#L582

**Comment by lojzatran** [comment]
It was probably fixed here: https://github.com/sphereio/sphere-node-sdk/commit/adbc5ce7655cb7dcb8d7117f2d1f1613508b9369
