### ISSUE TITLE
Missing StatusCode in Response

### ISSUE THREAD

**Issue by casabian** [sphereio/sphere-node-sdk#147]
### Expected behavior
Expecting a stausCode 404 for errorType:"NotFound" in OrderService

### Actual behavior
                "errorMessage": "Endpoint '/...../orders/<ORDERID>' not found.",
                "errorType": "NotFound",
                "stackTrace": []
### Steps to reproduce the behavior
Request an non-existing Order by ID

**Comment by emmenko** [comment]
The status code should be set. Are you sure it's not there? What object is the one you posted? What sdk version are you using?

**Comment by Siilwyn** [comment]
Just tested it and I receive the `404` status code.

Using `client.orders.byId('123').fetch()`.

Returns:
```
{ NotFound: Endpoint '/.../orders/123' not found.
    at OrderService.BaseService._wrapResponse (...)
  message: 'Endpoint \'/.../orders/123\' not found.',
  body:
   { statusCode: 404,
     message: 'Endpoint \'/.../orders/123\' not found.',
     originalRequest: { endpoint: '/orders/123', options: [Object] } },
  name: 'NotFound',
  statusCode: 404,
  code: 404 }
```
