### ISSUE TITLE
npm WARN sphere-node-sdk@1.15.1 requires a peer of underscore@>=1.8.0 but none was installed.

### ISSUE THREAD

**Issue by ralfr** [sphereio/sphere-node-sdk#151]
Trying to run the simpe example. `npm install` works fine. However, when trying to run `node hello.js` I get:

```
npm WARN sphere-node-sdk@1.15.1 requires a peer of underscore@>=1.8.0 but none was installed.
npm WARN sphere-node-sdk@1.15.1 requires a peer of underscore-mixins@^0.1.x but none was installed.
```

Any idea?

**Comment by emmenko** [comment]
Well, those are [peer dependencies](https://nodejs.org/en/blog/npm/peer-dependencies/), which means they are not installed automatically when you install the node-sdk.
You need to explicitly install them.
