### ISSUE TITLE
Be resilent against network level errors

### ISSUE THREAD

**Issue by nkuehn** [sphereio/sphere-node-sdk#170]
### Expected behavior

The Network ist not reliable.  commercetools is a distributed system.  All tooling needs take that into account and be resilent. SDKs are meant to provide the functionality that every implementation needs so it's not repeated..  

Specifically: Fine grained control over retry behavior should be offered to implementing tools (e.g. our CLIs) so that not everybody is doing the same errors gain.   Focus areas (need to be individually controllable)
- network level fails (socket hangup, mostly due to lost packet, dropped connection etc)
- network timeouts
- retry on concurrent modifications
### Actual behavior

All calls, e.g. in a big bulk import, fail hard e.g. on socket hang up.  This is OK as a default, but it's not usable in production bulk imports / syncs etc.  
### Steps to reproduce the behavior

Try any bigger thing over WiFi, e.g. category sync, product-csv-sync etc. pp.   Fail, try again. Fail, try again.

**Comment by skyriakou** [comment]
@nkuehn  Is this still relevant issue? Thanks

**Comment by butenkor** [comment]
We have already build in/default repeater for network errors here: https://github.com/sphereio/sphere-node-sdk/blob/master/src/coffee/client.coffee#L236

**Comment by nkuehn** [comment]
@skyriakou  not in this SDK any more. we can close this IMHO.
