### ISSUE TITLE
Cannot initialize module at all

### ISSUE THREAD

**Issue by tnolet** [sphereio/sphere-node-sdk#173]
### Expected behavior

require the SphereClient Class and instantiate it with credentials.
### Actual behavior

SphereClient is undefined
### Steps to reproduce the behavior

```
const config = require('config')
const SphereClient = require('sphere-node-sdk').SphereClient
const client = new SphereClient({
  config: {
    project_key: config.commercetools.project,
    client_id: config.commercetools.clientId,
    client_secret: config.commercetools.clientSecret
  }
})

client.products.fetch()
    .then(res => {
      console.log(res)
    })
```

this does not work. SphereClient is undefined.

**Comment by tnolet** [comment]
turns out your default NPM package is already on the 2.0 alpha branch. You might want to switch that back and publish the latest stable 1.x version as the default npm install. Now anyone following the documentation will not be able to get started.

**Comment by hisabimbola** [comment]
This has been fixed, please reopen if otherwise.
