### ISSUE TITLE
Support gzip compression by default for all requests

### ISSUE THREAD

**Issue by mmoelli** [sphereio/sphere-node-sdk#196]
### Expected behavior
- All requests should use gzip as default to improve performance

### Actual behavior
- At the moment, no requests sent via the node-sdk are using this, which leads to performance degradation

### Steps to reproduce the behavior
---

**Comment by Siilwyn** [comment]
@emmenko how does the new SDK handle this?

**Comment by emmenko** [comment]
I haven't looked into it yet, I've opened a new issue https://github.com/commercetools/nodejs/issues/79

For this sdk, since we're using `request`, it's just a matter of [enabling it](https://github.com/request/request#requestoptions-callback) `gzip: true`.
