### ISSUE TITLE
Enable markMarchingVariants

### ISSUE THREAD

**Issue by mmoelli** [sphereio/sphere-node-sdk#207]
### Expected behavior
Via the SDK, we need the option to set ```markMatchingVariant``` to ```true``` to enable this behaviour. (http://dev.commercetools.com/http-api-projects-products-search.html#matchingVariant)

### Actual behavior
At the moment, the parameter is not supported in the search command.

**Comment by hisabimbola** [comment]
This already exists in the new SDK [here](https://github.com/commercetools/nodejs/issues/100), we recommend all to use the new SDK....
