### ISSUE TITLE
Improve fetch all method

### ISSUE THREAD

**Issue by lojzatran** [sphereio/sphere-node-sdk#223]
### Description
When you doing fetch all, it should fetches all items with minimum requests.

### Current Behavior
Right now fetch all has a limit of 50 items per request and if there are more than 50 items, it needs to fetch multiple times.

### Context
Because of the multiple fetches, there are more queries and the whole fetch all method is slower.

### Possible Solution
Increase the limit number of items to 500, which is the maximum in commercetools platform.

**Comment by hisabimbola** [comment]
Instead of using `fetchAll` you can use the normal `fetch` and specify the limit

**Comment by hisabimbola** [comment]
Also, in place like impex where this module is being used, fetching 500 items by default to the browser might not be too performant..

**Comment by lojzatran** [comment]
@hisabimbola The fix that I try to address here affects only when you do `all().fetch()`. The previous code was fetching 50 items per request, which has the effect of making more requests when you have more than 50 items. I just want to raise it to the maximum 500, which results in less requests in case of `all().fetch()`. This does not affect fetching without `all()`.

**Comment by hisabimbola** [comment]
Okay, that's fine

**Comment by lojzatran** [comment]
Since this can be a breaking change, I will now make the limit parameter configurable and configure it in the modules that need it.
