### ISSUE TITLE
Use price selection with Product Projection Search service

### ISSUE THREAD

**Issue by sallar** [sphereio/sphere-node-sdk#228]
### Description

Currently it's not possible to enable Price Selection when using Product Projection Search (or other services). It is possible to send `priceCurrency`, `priceCountry` etc through the REST API, but this SDK doesn't allow sending those at least from what I have figure it out so far.

### Expected Behavior

It should be possible to enable Price Selection using the NodeJS sdk.

**Comment by LEQADA** [comment]
What do you mean under "Price Selection"? Like "Give me products with price more than 256 cents"?
Something like this `masterVariant(prices(value(centAmount > 256)))`?

**Comment by sallar** [comment]
No, according to CT API docs, price selection finds the best matching price from the prices array. For example if I pass in "priceCountry=US&priceCurrency=USD" the resulting variant will include a "price" key in addition to "prices" array.

**Comment by sallar** [comment]
@LEQADA for example this query returns the correct result now: `https://api.sphere.io/PROJECT_KEY/product-projections/search?priceCurrency=EUR&priceCountry=FI`

**Comment by LEQADA** [comment]
Now I'm confused. Do you want to say "Give me only those products which has price with priceCurrency=EUR and priceCountry=FI"?

**Comment by sallar** [comment]
@LEQADA No, im not trying to "filter" products. Im trying to enable "Price Selection". [See this section of the docs](http://dev.commercetools.com/http-api-projects-products-search.html#search-productprojections) and keys: `priceCountry`, `priceCurrency`. Basically we need to send a few more query strings.

and this is how the variant response looks like with those options:

![image](https://cloud.githubusercontent.com/assets/768052/25798261/1f6ddbbe-33e9-11e7-983b-660661a4f994.png)

**Comment by hisabimbola** [comment]
@sallar, thanks for your explanation, I hope it clears it

...and I look into this today and confirmed that it's missing from the SDK, We will prioritize and add it here and new SDK [#154](https://github.com/commercetools/nodejs/issues/154)

**Comment by LEQADA** [comment]
@sallar oh, now I understand what you mean. 
Maybe use this kind of GraphQL query instead?

```
query Sphere {
  products {
    results {
      masterData {
        staged {
          allVariants{
            price(currency:"EUR", country:"DE"){
              id
              value{
                centAmount
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by butenkor** [comment]
As @sallar pointed out price selection is currently not supported by neither this nor new nodejs SDK.

**Comment by junajan** [comment]
thx for releasing it
