### ISSUE TITLE
Possible DoS reported in a dependency

### ISSUE THREAD

**Issue by mdeolmos** [sphereio/sphere-node-sdk#242]
### Description

I'm getting the warning described below when I build my app.

```js
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

I realize that the lates sdk (1.21.1) is using it.  It looks like an important security issue.

```
`-- sphere-node-sdk@1.21.1
  `-- sphere-node-utils@0.8.7
    +-- bunyan@1.8.4
    | `-- mv@2.1.1
    |   `-- rimraf@2.4.5
    |     `-- glob@6.0.4
    |       `-- minimatch@3.0.4  deduped
    `-- load-module-pkg@0.1.0
      `-- cwd@0.5.1
        `-- look-up@0.2.3
          `-- multimatch@1.0.1
            `-- minimatch@1.0.0

### Expected Behavior
I would expect to not have DoS warnings

### Possible Solution
update to minimatch 3.0.2 ?

**Comment by wizzy25** [comment]
Hello @mdeolmos, thanks for reporting this issue. Unfortunately, one of the deprecated `minimatch` versions is used by a dependency of `jasmine-node`, which we use for testing, and this has not been updated to reflect this change. We will be monitoring the situation and will update it as soon as it becomes available.

Also, this repository is deprecated and you're advised to use [this](https://github.com/commercetools/nodejs) instead. A migration can be found [here](https://commercetools.github.io/nodejs/sdk/upgrading-from-sphere-node-sdk.html)

**Comment by mdeolmos** [comment]
Thanks for the update @wizzy25!
