### ISSUE TITLE
Update "request" dependency to latest bug fix version

### ISSUE THREAD

**Issue by butenkor** [sphereio/sphere-node-sdk#258]
### Description
Currently we use outdated `request` dependency which on http requests throws confusing error 
```      
"stack": "HttpError: unexpected end of file\n    at ProductTypeService.BaseService._wrapResponse (/app/node_modules/sphere-node-sdk/lib/services/base.js:468:21)\n    at /app/node_modules/sphere-node-sdk/lib/services/base.js:365:40\n    at Request._callback (/app/node_modules/sphere-node-sdk/lib/connect/rest.js:166:14)\n    at self.callback (/app/node_modules/sphere-node-sdk/node_modules/request/request.js:360:22)\n    at emitOne (events.js:96:13)\n    at Request.emit (events.js:188:7)\n    at Gunzip.<anonymous> (/app/node_modules/sphere-node-sdk/node_modules/request/request.js:1153:12)\n    at emitOne (events.js:101:20)\n    at Gunzip.emit (events.js:188:7)\n    at Zlib._handle.onerror (zlib.js:374:10)"
```
Issue seems to be related to `request` library used by SDK: https://github.com/request/request/pull/2176 and was fixed in version 2.72.0.

### Expected Behavior
Should use latest `request` bug fix version: 2.85.0 (or at least the version which fixes described issue: 2.72.0)

### Current Behavior
Uses outdated `request` version: 2.54.x

**Comment by daern91** [comment]
Hi @butenkor, could you please let me know why we still use this one since its deprecated?

**Comment by butenkor** [comment]
Hi. Some older projects still use old SDK as migration takes time/money so it is often not an option for existing and already working customer projects. Even our own open source repositories are still not completely migrated. 

I think that deprecation notice is not enough to drop its development completely. Currently it is just a hint that new features will not be provided here anymore but for the sake of security and other bugs it should still be supported. 

In order to drop its support completely one would need to find out who is using it, notify about the change and discuss/set deadline for migration.

**Comment by daern91** [comment]
Makes sense. Thanks a lot for explaining, @butenkor.
