### ISSUE TITLE
In case of non 20x response, log the X-Correlation-ID Header

### ISSUE THREAD

**Issue by hajoeichler** [sphereio/sphere-node-sdk#58]

**Comment by emmenko** [comment]
What's this? More explanation on the requirements please

**Comment by hajoeichler** [comment]
The correlation Id header gives you an identifier. With this identifier we have one single string where we can accumulate all logs from all different backend services for a failing request. So when you get an error from sphere and have questions, it would be the best to provide this identifier to the support team as they can easily find all relevant information about the problematic call.

**Comment by emmenko** [comment]
Hmm ok. Is this header always present? Also, the SDK doesn't log anything, it's up to the applications to do that. I guess I will just pass the header along with the `Error`

**Comment by hajoeichler** [comment]
good solution - let's document it somewhere ;)

**Comment by emmenko** [comment]
I'm already on it, PR will follow soon ;)

**Comment by svenmueller** [comment]
+1

2015-03-18 15:00 GMT+01:00 Nicola Molinari <notifications@github.com>:

> I'm already on it, PR will follow soon ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sphereio/sphere-node-sdk/issues/58#issuecomment-82986542>
> .
>



-- 

Sven Müller
Product Software Architect

[image: commercetools logo] <http://www.commercetools.com>

E. sven.mueller@commercetools.de
T. +49 (89) 99 82 996-23 <+49+(89)+99+82+996-23>

Adams-Lehmann-Str. 44
80797 München
commercetools.de <http://www.commercetools.de>

-- 


commercetools GmbH
SPHERE.IO <http://www.sphere.io> - Enterprise E-Commerce Software without 
Enterprise Hassles

[image: e-commerce banner] <http://www.internetworld-messe.de/>

Amtsgericht München, HRB 161496
Geschäftsführer: Denis Werner, Dirk Hörig, Dr. Robert Zores

**Comment by yanns** [comment]
Why only in case of non 20x responses???

I think the deprecation header will be used most of the case with a 20x response.

**Comment by emmenko** [comment]
The header is always present, see PR https://github.com/sphereio/sphere-node-sdk/pull/59/files

**Comment by yanns** [comment]
sorry, I mix the correlation ID and the deprecation header...

**Comment by emmenko** [comment]
:+1:
