### ISSUE TITLE
Road to v2.x

### ISSUE THREAD

**Issue by emmenko** [sphereio/sphere-node-sdk#63]
The next major release would be a big internal refactoring, needed to implement some new cool features.
- [x] rewrite using ES6
- [x] should work in node.js + browser environment
- [ ] node versions support
  - [ ] 0.10 ??
  - [ ] 0.12
  - [ ] 4 / 5
- [ ] public API should stay the same (if possible)
  - [ ] migration guide (breaking changes)
    - options passed to `SphereClient`
    - services have only methods that they need
    - new `productProjectionsService`
    - sync utils now just have a `buildActions` function
- [ ] support all API endpoints by default
- [ ] support new oauth password flow (/me endpoint)
- [ ] allow to pass only an access_token, without client credentials
- [x] use object compositions instead of class inheritance
- [ ] new TaskQueue implementation
  - [x] check for (valid) auth_token, otherwise block new tasks until new token is retrieved
  - [ ] retrieval mechanism for failure requests (timeout, service unavailable, ...)
  - [ ] hook mechanism when retrying for custom implementations (e.g.: 409)
- [ ] migrate functional utils such as `.process()`
- [x] simplified sync implementation
  - [x] support for products actions
  - [x] support for categories actions
  - [ ] support for inventories actions
  - [ ] support for orders actions
- [x] generic implementation of `Promise` (no required promise library), let the application choose
- [x] make the client configurable (host, headers, ...)
- [x] allow to register custom services
- [x] make it easy testable my injecting a http mock client
- [x] expose http components to be able to reuse them for other implementations (e.g.: internal API)
- [ ] ~~chained service functions should return an immutable object~~
- [ ] ability to optionally stream requests (easy possible because of `node-fetch`)
- [ ] migrate response handlers (original request headers, errors, ...)
- [ ] introduce `*Builder` functions for things like actions, query predicates, ...
- [ ] documentation with https://www.gitbook.com/
  - [ ] API / Glossary
  - [ ] Guides / examples
  - [ ] Best practices
  - [ ] Contribution guidelines made easy
  - [ ] Flowtypes for easy documentation (glossary)
  - [ ] automatic changelogs + release pages
- [ ] inline / annotated jsdoc (e.g.: http://underscorejs.org/docs/underscore.html)
- [x] browser testing (https://www.npmjs.com/package/browser-run)
  - [ ] integration tests fail because https://auth.sphere.io doesn't support CORS yet

Extra:
- [ ] `sphere-node-test-addons` for bootstrapping data, setting up tests, and so on (decide whether to include it in the sdk or make it a separate package)
- [ ] extract `sync` utils for `sphere-node-sync-actions`

**Comment by daliwali** [comment]
I just want to point out that the only truly necessary items in this list are:

- Making the client configurable
- Fixing authentication
- Making sure it works in a browser

This is actually a pretty low bar and if we can get that done soon I think we can postpone rewriting it. I don't even care that it's written in CoffeeScript, done is better than perfect.

**Comment by jayS-de** [comment]
- [ ] Support oauth clients with scope other than manage_project

**Comment by nkuehn** [comment]
any plans to do the rebranding to commercetools in the turn on the 2.0 release?

**Comment by emmenko** [comment]
@nkuehn we can do that yes

**Comment by tnolet** [comment]
Hi, is this project still alive? What's the ETA on this?

**Comment by emmenko** [comment]
@tnolet hey, yes it is. Hopefully by the end of the year we have a stable `2.0` version. You can see the progress in the [`rewrite-2.0`](https://github.com/sphereio/sphere-node-sdk/tree/rewrite-2.0) branch.

At the moment, we are releasing `alpha` versions, the latest one being `2.0.0-alpha.45` at the time of writing. It's a stable version and it's currently being used in a production application. It's still not feature complete, that's why it's still in `alpha`.

**Comment by tnolet** [comment]
@emmenko, that's good news! Thanks for the quick reply

**Comment by nkuehn** [comment]
@emmenko  "allow to pass only an access_token" is already working for me (just pass it as `auth` in the clientConfig instead of `creentials`

**Comment by kevinrambaud** [comment]
Is the development of v2 still active ?

**Comment by hisabimbola** [comment]
Not active anymore, we have a new [JS-SDK](https://commercetools.github.io/nodejs/sdk/api/sdkClient.html) here
