### ISSUE TITLE
Empty task object in client error

### ISSUE THREAD

**Issue by Sikian** [sphereio/sphere-node-sdk#67]
If the example in http://sphereio.github.io/sphere-node-sdk/ is copied and executed, the following error will come up:
```TypeError: undefined is not a function
  at ProductService.BaseService._get (/Users/sikian/Projects/testsphere/node_modules/sphere-node-sdk/lib/services/base.js:297:23)```

This is due to `task: {}`, as BaseService._task will be set to empty in the initializer:
```this._task = options._task```
Please consider using underscore's `isEmpty(options._task)` or editing the wiki in order to avoid this pitfall again.

Thanks!

**Comment by emmenko** [comment]
Which example are you referring to?

PS: the `_task` is initialized here actually https://github.com/sphereio/sphere-node-sdk/blob/master/src/coffee/client.coffee#L216

**Comment by Sikian** [comment]
Wow, this was so long ago I don't even remember writing it. I'll try to recall what I was trying to convey and get back to you.

**Comment by emmenko** [comment]
Yeah, sorry. I actually saw this issue today :)

**Comment by Sikian** [comment]
As far as I can remember, I was having some troubles because some services -- which I imply is the ProductService due to the stack trace -- was giving that error as no `._task` was being set in the BaseService initializer. 

Unfortunately I can't recall what was I doing to reproduce that case, sorry :(

**Comment by emmenko** [comment]
Ok, if you encounter this problem again please let me know! :)
