### ISSUE TITLE
Support sync for product types

### ISSUE THREAD

**Issue by hajoeichler** [sphereio/sphere-node-sdk#69]

**Comment by mmoelli** [comment]
@butenkor @hajoeichler 
* What kind of actions should this sync support? Can we focus for the initial release? (http://dev.commercetools.com/http-api-projects-productTypes.html#update-product-type)
* When the sync actions are included in the SDK, which library is going to use it?

**Comment by butenkor** [comment]
@mmoelli node SDK already can create/update product type. It can not calculate differences between 2 instances of product type and create update actions yet. It should create new attributes and update existing attributes with new enum values.

**Comment by mmoelli** [comment]
@butenkor Does this include only plain or also localized enum values, as these are to different update actions?

**Comment by butenkor** [comment]
It should support both.

**Comment by mmoelli** [comment]
So the difference analysis should lead to update actions with the following type.
* ```addPlainEnumValue```
* ```addLocalizedEnumValue```
* ```addAttributeDefinition```

@PhilippSpo @hajoeichler Could you please sit together and discuss what could be a possible integration path for this feature as well as a brief estimate. Thanks!
