### ISSUE TITLE
Give more details on 400 responses

### ISSUE THREAD

**Issue by hajoeichler** [sphereio/sphere-node-sdk#70]
I used a wrong id for my parent category during creation.

When I `prettify` the error I get in the `catch()` part, I only see `BadRequest: Request body does not contain valid JSON`, but the API actually returns more information:

```
"statusCode": 400,
  "message": "Request body does not contain valid JSON.",
  "errors": [
    {
      "code": "InvalidJsonInput",
      "message": "Request body does not contain valid JSON.",
      "detailedErrorMessage": "parent -> id: Invalid UUID: '2833'"
    }
  ],
```

I would like to get the `detailedErrorMessage` too.

**Comment by emmenko** [comment]
That's because the error you catch is a real `Error` type. So when you log it you get the `message`. To access to all response body, just do `_.prettify(error.body)`.

See http://sphereio.github.io/sphere-node-sdk/classes/SphereClient.html#error-types

**Comment by hajoeichler** [comment]
That's what I do https://github.com/sphereio/sphere-category-sync/blob/master/src/coffee/apiclient.coffee#L58
Still I don't see the `detailedErrorMessage` property.

**Comment by emmenko** [comment]
Actually you don't :)

```
Error on updating category:\n#{_.prettify err}
```

should be

```
Error on updating category:\n#{_.prettify err.body}
```

**Comment by hajoeichler** [comment]
thx! will adapt my code then

**Comment by emmenko** [comment]
Also I wouldn't log it as a string, instead

```coffescript
@logger.error 'Error on updating category', {source: context.sourceInfo, error: err.body}
```
