### ISSUE TITLE
statusCode vs code

### ISSUE THREAD

**Issue by hajoeichler** [sphereio/sphere-node-sdk#71]
```
...then (result) ->
  result.statusCode
.catch (err) ->
  err.code
```

It would be nice if we can align the two properties. I vote to change both to `statusCode`.

**Comment by emmenko** [comment]
Hmm, I guess so.
For the `Errors` you can change it here https://github.com/sphereio/sphere-node-sdk/blob/master/src/coffee/errors.coffee
