### ISSUE TITLE
Remove default sorting by Id

### ISSUE THREAD

**Issue by hajoeichler** [sphereio/sphere-node-sdk#77]
See https://github.com/sphereio/sphere-node-sdk/commit/c4554e2e9a294fe000644244389ec94b92116af8#commitcomment-12173426

**Comment by emmenko** [comment]
See https://github.com/sphereio/sphere-jvm-sdk/issues/568#issuecomment-121532181

:)

**Comment by hajoeichler** [comment]
What about this line then?
https://github.com/sphereio/sphere-node-sdk/blob/master/src/coffee/services/base.coffee#L283

**Comment by emmenko** [comment]
This is still traversing, so there should be a default sorting

**Comment by yanns** [comment]
`service.where('masterData(current(masterVariant(sku = "5183189"')))).fetch()` should not be sorted IMO.

**Comment by emmenko** [comment]
It doesn't :)

Only traversing pages has a default sorting, so when you do:

```js
service.process(fn)

// or
service.all().fetch()
```

**Comment by hajoeichler** [comment]
Got it, thx!

**Comment by yanns** [comment]
great explanation, thx! 
:+1:
