### ISSUE TITLE
More detailed error messages required

### ISSUE THREAD

**Issue by panshul007** [sphereio/sphere-node-sdk#78]
I was importing prices using price-importer through sphere-node-cli
I got an error: `Duplicate price scope: (currency: EUR, country: AT, validFrom: 2015-06-30T22:00:00.000Z, validUntil: 2099-12-30T23:00:00.000Z)`

This does not help me much in finding the source of error. Would be good to have more detailed message with details about the product or variant sku.
<img width="1440" alt="screen shot 2015-07-23 at 09 40 56" src="https://cloud.githubusercontent.com/assets/745298/8846578/a7c411c4-3128-11e5-99e0-a86626e8000a.png">

**Comment by emmenko** [comment]
You just have to print `error.body`. What you see is `error.message`. Also not an issue of the sdk.

**Comment by panshul007** [comment]
can u please suggest where this change needs to be made? in the sphere-importer or in the node-cli?

**Comment by emmenko** [comment]
@panshul007 
Try it here https://github.com/sphereio/sphere-product-import/blob/master/lib/product-import.coffee#L43

```coffeescript
@_processBatches(chunk).then -> cb()
.catch (err) -> cb(err.body)
```
