### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by panshul007** [sphereio/sphere-node-sdk#79]
I get the following error message from custom-objects service:

    { [BadRequest: Request body does not contain valid JSON.]
      message: 'Request body does not contain valid JSON.',
      body:
         { statusCode: 400,
          message: 'Request body does not contain valid JSON.',
           errors: [ [Object] ],
           originalRequest: { endpoint: '/orders', payload: [Object] } },  
     name: 'BadRequest',
     statusCode: 400,
     code: 400 }

isn't this too much redundant information?

**Comment by emmenko** [comment]
The object you get is an instance of the `Error` type with some basic info. In addition there is a `body` field which contains the JSON response payload from the API.
