### ISSUE TITLE
node sdk timeout is too short

### ISSUE THREAD

**Issue by sebbulon** [sphereio/sphere-node-sdk#95]
we periodically run into timeouts - even though I can't find a 408 in the CTP logs, and no specifically long running processes. This concludes that the Node SDK timeout is kicking in - it should either be configurable or be more flexible so that impex jobs can run more reliably

examples:
```
statusCode: 500,
  message: 'ESOCKETTIMEDOUT'
```

or

```
{ statusCode: 500,
  message: 'connect ETIMEDOUT',
  originalRequest: { endpoint: '/product-projections?where=masterVariant(sku%20in%20(%22I020151_1%22))%20or%20variants(sku%20in%20(%22I020151_1%22))&limit=0&sort=id%20asc&staged=true' } }
```

**Comment by emmenko** [comment]
The request timeout is fully configurable. The client using the sdk has to take care of this. Please open the issue in the specific project.
