### ISSUE TITLE
Add plain JS basic example

### ISSUE THREAD

**Issue by lauraluiz** [sphereio/sphere-node-sdk#97]
I cannot find a plain example in JavaScript (no CS) that is working, having only the initialization of the client with credentials and a simple request to test it. Adapting the examples that I find generates wrong base configuration (`authUrl` appears to be undefined), so it seems something is missing in my code.

For these situations, it would be very useful to have it in JS.

**Comment by emmenko** [comment]
Can you post your code to see what you are doing wrong?

FYI: the upcoming `2.0` version is written in JS, documentation / examples will be in JS as well ;)

**Comment by lauraluiz** [comment]
Great! Unfortunately the code was not in my hands so I cannot copy it, but I was helping in looking for the problem and I couldn't find a plain example to follow anyway.
But with the "FYI" this issue will be solved, so we can close it :)
